# Generated by Django 4.2 on 2023-05-19 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000000)),
                ('created_At', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post_read', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
